name: 🚀 Release

on:
  workflow_dispatch:

env:
  BUCKET: 's3://javiercarrillo.dev'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: 💼 Configure Git user
        run: |
          git config user.name "javiercm1410"
          git config user.email "javiercm@dump.com"

      - name: 🟢 Configure Node.js on runner
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'

      - name: 🟡 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: 📦 Install package dependencies using lockfile
        run: npm ci

      - name: 📦 Build application
        run: npm run build

      - name: 🚀 Run new version
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: 🚀 Upload binaries to S3
        run: |
          aws s3 sync ./dist ${BUCKET}
          aws s3 cp ./package.json ${BUCKET}
